linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - goimports
    - misspell
    - unconvert
    - gocritic

linters-settings:
  goimports:
    local-prefixes: github.com/phobologic/repoguide

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
