version: 2

builds:
  - id: repoguide
    main: .
    binary: repoguide
    ldflags:
      - -s -w -X main.version={{.Version}}
    env:
      - CGO_ENABLED=1
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    overrides:
      - goos: darwin
        goarch: amd64
        env:
          - CGO_ENABLED=1
          - CC=clang -arch x86_64
      - goos: linux
        goarch: amd64
        env:
          - CGO_ENABLED=1
          - CC=zig cc -target x86_64-linux-musl
        goamd64: v1
      - goos: linux
        goarch: arm64
        env:
          - CGO_ENABLED=1
          - CC=zig cc -target aarch64-linux-musl

archives:
  - formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"

homebrew_casks:
  - name: repoguide
    binaries:
      - repoguide
    homepage: https://github.com/phobologic/repoguide
    description: Generate tree-sitter repository maps in TOON format
    directory: Casks
    repository:
      owner: phobologic
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
