package main

import (
	"fmt"
	"io"
)

const headerBase = `# Repository Map

This is a repository map generated by repoguide. It shows the structure,
key symbols, and dependencies of the codebase in TOON format.

## How to read this map

- **files**: Source files ranked by importance (PageRank over the dependency
  graph). Higher rank = more central to the codebase. Start here to find
  the most important files.
- **symbols**: Exported definitions (classes, functions, methods) with file
  location and signature. Use as a lookup index when you know the name —
  not as a scanning surface.
- **dependencies**: Cross-file references showing which files depend on
  which. The "symbols" column lists the specific symbols referenced.

## Usage tips

- **Test files are excluded by default.** This map covers production code only.
  Run with ` + "`--with-tests`" + ` to include test files.
- **To find all callers of a function:** run ` + "`repoguide --symbol <name>`" + `
  instead of grep. Returns the definition location, every call site with
  exact file and line number, and the function's callees — in one command.
- **Focused queries include a ` + "`callsites`" + ` table** with exact file+line for
  every call occurrence. Use those line numbers for ` + "`Read(offset=N)`" + ` instead
  of scanning.

## TOON format

Scalar: ` + "`key: value`" + `
Table: ` + "`name[count]{col1,col2,...}:`" + ` followed by indented rows of
comma-separated values.

---`

const headerWithTests = `# Repository Map

This is a repository map generated by repoguide. It shows the structure,
key symbols, and dependencies of the codebase in TOON format.
Test files are included (` + "`--with-tests`" + `).

## How to read this map

- **files**: Source files ranked by importance (PageRank over the dependency
  graph). Higher rank = more central to the codebase. Start here to find
  the most important files.
- **symbols**: Exported definitions (classes, functions, methods) with file
  location and signature. Use as a lookup index when you know the name —
  not as a scanning surface.
- **dependencies**: Cross-file references showing which files depend on
  which. The "symbols" column lists the specific symbols referenced.

## Usage tips

- **To find all callers of a function:** run ` + "`repoguide --symbol <name>`" + `
  instead of grep. Returns the definition location, every call site with
  exact file and line number, and the function's callees — in one command.
- **Focused queries include a ` + "`callsites`" + ` table** with exact file+line for
  every call occurrence. Use those line numbers for ` + "`Read(offset=N)`" + ` instead
  of scanning.

## TOON format

Scalar: ` + "`key: value`" + `
Table: ` + "`name[count]{col1,col2,...}:`" + ` followed by indented rows of
comma-separated values.

---`

// writeOutput writes the TOON data to w, prepending the agent context header
// unless raw is true. withTests controls which header variant is used.
func writeOutput(w io.Writer, toonData string, raw, withTests bool) {
	if !raw {
		h := headerBase
		if withTests {
			h = headerWithTests
		}
		_, _ = fmt.Fprintln(w, h)
	}
	_, _ = fmt.Fprintln(w, toonData)
}
