package main

import (
	"fmt"
	"io"
)

const agentHeader = `# Repository Map

This is a repository map generated by repoguide. It shows the structure,
key symbols, and dependencies of the codebase in TOON format.

## How to read this map

- **files**: Source files ranked by importance (PageRank over the dependency
  graph). Higher rank = more central to the codebase. Start here to find
  the most important files.
- **symbols**: Exported definitions (classes, functions, methods) with file
  location and signature. Use this to find where things are defined.
- **dependencies**: Cross-file references showing which files depend on
  which. The "symbols" column lists the specific symbols referenced.

## TOON format

Scalar: ` + "`key: value`" + `
Table: ` + "`name[count]{col1,col2,...}:`" + ` followed by indented rows of
comma-separated values.

---`

// writeOutput writes the TOON data to w, prepending the agent context header
// unless raw is true.
func writeOutput(w io.Writer, toonData string, raw bool) {
	if !raw {
		_, _ = fmt.Fprintln(w, agentHeader)
	}
	_, _ = fmt.Fprintln(w, toonData)
}
